[toolchain]

[features]
resolution = true
skip-lint = false

[programs.devnet]
lending2 = "D1HBoAv1A5Jy72DaStawF5UkZCTMexXjvVbb1h5bNV5f"

[programs.localnet]
lending2 = "D1HBoAv1A5Jy72DaStawF5UkZCTMexXjvVbb1h5bNV5f"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
